# Generated by Django 5.2.16 on 2026-07-21 14:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('CUSTOMER', 'customer'), ('ADMIN', 'admin'), ('SELLER', 'seller')], default='CUSTOMER', max_length=20)),
                ('isActive', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SellerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doorNo', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=255)),
                ('landMark', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='INDIA', max_length=30)),
                ('companyName', models.CharField(max_length=150)),
                ('contactPerson', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('purpose', models.CharField(choices=[('WAREHOUSE', 'Warehouse / Pickup Point'), ('REGISTERED_OFFICE', 'Registered Office'), ('RETURN_LOCATION', 'Return Location')], default='WAREHOUSE', max_length=20)),
                ('isPrimary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'SELLER'}, on_delete=django.db.models.deletion.CASCADE, related_name='seller_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sellerAddresses',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doorNo', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=255)),
                ('landMark', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='INDIA', max_length=30)),
                ('fullName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('addressType', models.CharField(choices=[('HOME', 'home'), ('WORK', 'work'), ('OTHER', 'other')], default='HOME', max_length=10)),
                ('isDefault', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customerAddresses',
                'ordering': ['-isDefault', '-createdAt'],
            },
        ),
    ]
