# Generated by Django 5.2.16 on 2026-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='addressType',
            new_name='address_type',
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='doorNo',
            new_name='door_no',
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='landMark',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='selleraddress',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='selleraddress',
            old_name='contactPerson',
            new_name='contact_person',
        ),
        migrations.RenameField(
            model_name='selleraddress',
            old_name='doorNo',
            new_name='door_no',
        ),
        migrations.RenameField(
            model_name='selleraddress',
            old_name='isPrimary',
            new_name='is_primary',
        ),
        migrations.RenameField(
            model_name='selleraddress',
            old_name='landMark',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='selleraddress',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='isActive',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='isDefault',
        ),
        migrations.RemoveField(
            model_name='users',
            name='isVerified',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='customeraddress',
            table='customer_addresses',
        ),
        migrations.AlterModelTable(
            name='selleraddress',
            table='seller_addresses',
        ),
    ]
